[package]
name = "mwget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.18"
chrono = "0.4.19"
futures-util = "0.3.21"
regex = "1.6.0"
regex-syntax = "0.6.27"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.20.0", features = ["full"] }
wiki = { path = "../" }
